import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "IS TimeFlow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-100 h-full dark">
      <body className="antialiased h-full">
        {children}
      </body>
    </html>
  );
}
