import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import DevelopmentBanner from "./components/DevelopmentBanner";

export const metadata: Metadata = {
  title: "IS TimeFlow",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`bg-gray-100 h-full dark ${poppins.className}`}>
      <body className="antialiased h-full">
        <div className="h-full flex flex-col">
          <Header />
          <DevelopmentBanner />
          <main className="space-y-6 lg:space-y-10 p-4 sm:p-6 lg:p-8 flex flex-col grow dark:bg-slate-900">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
